### ISSUE TITLE
There was a problem returning information from the computer group you selected

### ISSUE THREAD

**Issue by joshnovotny** [chrisgzim/Jamf-API-Recovery-Lock-by-Group#14]
Hello,

Getting this error when running the version of the "lazy" script you pushed out this morning:

![Screenshot 2024-10-30 at 2 23 56 PM](https://github.com/user-attachments/assets/28523583-508a-45d8-bdb7-172faa2f2743)

I am for sure choosing a smart group as seen here:

![Screenshot 2024-10-30 at 2 22 25 PM](https://github.com/user-attachments/assets/9bdb3986-4d05-4489-9d9e-7f5201242591)

But still returning that error. There are 12 computers in that group and all of them are managed.

**Comment by chrisgzim** [comment]
Hey @joshnovotny,

I am going to do some testing today. This looks like you're doing the Computer Group ID > Static Password option. I may have missed something with that workflow. . . so I will see what I can find!

**Comment by chrisgzim** [comment]
Hey @joshnovotny, 

I believe I have identified the issue here. The problem is I cannot get the RSQL query to work properly for general.remoteManagement.managed. Therefore it is returning ALL computers in that request -- even those no longer "managed".

What happens is if I put in I have 2000 managed computers but I have 3000 total inventory records there is going to be a fringe group that won't be found. (Chances are all of the serials in the group you're sending the command to weren't returned in the original GET for their managementID.)

As a temporary workaround, can you put an absurdly large number in the "Number of Computers" field? 

I will put in some logic that will stop searching after it returns zero results in an update -- and just get rid of that field all together (since it wasn't really clear what that field was for).

 I will also keep working on the "on-demand" workflow. Trying to have a way to be able to grab the management ID regardless if you put serial or JSS ID.

**Comment by chrisgzim** [comment]
Hey @joshnovotny 

Would you try this version of the script? I can push it to main if this works more consistently? 

https://github.com/chrisgzim/Jamf-API-Recovery-Lock-by-Group/blob/development/swiftdialog_jproapilock.sh

**Comment by joshnovotny** [comment]
@chrisgzim Same group ID error with that version.

**Comment by chrisgzim** [comment]
@joshnovotny can you hit me up on Mac Admin's Slack. I am honestly stuck since I haven't been able to replicate in my testing.

**Comment by chrisgzim** [comment]
Just pushed out a new update of the development branch -- replaced the python and plutil commands to be jq instead. If you want to give that a try!

**Comment by joshnovotny** [comment]
Hey Chris, that got 3 out of 11 computers.

jq: parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 2, column 8
-e 2024-11-01 09:41:56 - number of computers returned:    1000

Should be a lot more than 1000 computers.

**Comment by chrisgzim** [comment]
Do you want to try this one? 

I made this to grab the management ID for each computer: https://github.com/chrisgzim/Jamf-API-Recovery-Lock-by-Group/blob/development/swiftdialog_jproapilock_on_demand_ID.sh

Hopefully this results in some success!

**Comment by joshnovotny** [comment]
Same error about the smart group.

```
-:1: parser error : StartTag: invalid element name
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title
 ^
-:1: parser error : Extra content at the end of the document
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title
 ^

-e 2024-11-05 07:26:49 - ERROR: Nothing returned from computer group 1225
CoreSVG has logged an error. Set environment variabe "CORESVG_VERBOSE" to learn more.
```

**Comment by chrisgzim** [comment]
@joshnovotny -- I realized I was looking at the wrong error and spending my efforts trying to fix something that didn't necessarily need fixing. 

I identified the issue was the trailing slash in the URL that we put in the beginning for the URL. For some reason it does NOT impact getting a token, but it does impact the ability to grab the group information. 

Apologies for this. Please check out the update to this one here: https://github.com/chrisgzim/Jamf-API-Recovery-Lock-by-Group/blob/development/swiftdialog_jproapilock_on_demand_ID.sh

**Comment by joshnovotny** [comment]
Hey Chris, that worked! Ran on all 11 Macbooks in that smart group.

**Comment by chrisgzim** [comment]
Awesome! I am going to work on cleaning up this script a bit, and then I will push this version to production
